FROM  trumanz/ubuntu14.04-dev

RUN wget http://download.eclipse.org/jetty/stable-9/dist/jetty-distribution-9.3.6.v20151106.tar.gz  && \
    tar xf  jetty-distribution-9.3.6.v20151106.tar.gz  -C  /opt/  && \
    ln -s  /opt/jetty-distribution-*   /opt/jetty  && \
    rm -rf  jetty-distribution-9.3.6.v20151106.tar.gz
