#From  trumanz/ubuntu14.04-dev
From   trumanz/ambarirepobase
maintainer  Truman Zhou <truman.ck.zhou@gmail.com>


#ADD apt.conf  /etc/apt/


RUN    apt-get update \
    && apt-get install -y  apache2  

    

